name: CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  # lint: # Turn on when linting issues are resolved
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 2

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.9"

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -e .[all]

  #     - name: Lint code
  #       run: |
  #         ruff check .

  test:
    # needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: sudo apt-get install -y graphviz rsync curl

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip packaging setuptools twine
          pip install --upgrade -e .[all]

      - name: Unit tests
        run: |
          pytest \
            --cov=autosubmit --cov-config=.coveragerc \
            --cov-report=xml:test/coverage.xml --cov-append \
            test/unit

      - name: Coverage report
        run: |
          coverage xml
          coverage report

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage_unit_py-${{ matrix.python-version }}
          path: coverage.xml
          retention-days: 7

  test-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: sudo apt-get install -y curl git graphviz rsync

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip packaging setuptools twine
          pip install --upgrade -e .[all]

      - name: Set up Git
        run: |
          # From: https://stackoverflow.com/questions/62960533/how-to-use-git-commands-during-a-github-action
          # Set up dummy configuration for integration tests.
          git --version
          git config --global user.email "test@bsc.es"
          git config --global user.name "GitHub Actions"

      # In GitHub Actions we run all the integration tests, including those that require
      # dependencies such as Docker (see `-m ''`, which means all markers). Read the
      # CONTRIBUTING.md file for details how to set up your environment to run these.
      - name: Integration tests
        run: |
          pytest \
            --cov=autosubmit --cov-config=.coveragerc \
            --cov-report=xml:test/coverage.xml --cov-append \
            test/integration \
            -m ''

      - name: Coverage report
        run: |
          coverage xml
          coverage report

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage_integration_py-${{ matrix.python-version }}
          path: coverage.xml
          retention-days: 7

  test-regression:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: sudo apt-get install -y curl graphviz rsync

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip packaging setuptools twine
          pip install --upgrade -e .[all]

      # Run regression tests
      - name: Regression tests
        run: |
          pytest \
            --cov=autosubmit --cov-config=.coveragerc \
            --cov-report=xml:test/coverage.xml --cov-append \
            test/regression \
            -m ''

      - name: Coverage report
        run: |
          coverage xml
          coverage report

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage_regression_py-${{ matrix.python-version }}
          path: coverage.xml
          retention-days: 7

  test-misc:
    runs-on: ubuntu-latest
    timeout-minutes: 5
