name: CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: SQLite v3.47.2 sample
    steps:
      - uses: actions/checkout@v4
      - name: Setup SQLite v3.47.2
        uses: actions/setup-sqlite@v1
        with:
          sqlite-version: 3.47.2
          sqlite-year: 2024
      - run: sqlite3 autosubmit.db