name: DOCKER

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      slurm:
        image: autosubmit/slurm-openssh-container:23-02-7-1
        ports:
          - 2222:2222
        options: --name slurm-container

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Copy access key
        run: |
          docker cp slurm-container:/root/.ssh/container_root_pubkey /tmp/container_root_pubkey

      - name: version autosubmit
        run: |
          pip install autosubmit
          autosubmit --version

      - name: config and install autosubmit
        run: |
          autosubmit configure
          autosubmit install

      - name: configure host
        run: |
          sudo bash -c 'mkdir /home/runner/.ssh/'
          sudo bash -c 'echo -e $"Host gen1\n  HostName localhost\n  User root\n  IdentityFile /tmp/container_root_pubkey\n  Port 2222\n   ForwardX11 yes" >> /home/runner/.ssh/config'

      - name: docker check
        run: |
          sleep 5
          docker ps -a
          docker images
          docker inspect slurm-container
          docker network ls

      - name: ssh access
        run: |
          cat /home/runner/.ssh/config
          cat /tmp/container_root_pubkey
          ssh root@localhost -p 2222 -i /tmp/container_root_pubkey sinfo
          ssh gen1

      - name: execute
        run: |
          autosubmit expid -H local -d test -min
          rm /home/runner/autosubmit/a000/conf/minimal.yml
          mkdir /home/runner/autosubmit/a000/proj
          sudo bash -c 'echo -e $"CONFIG:\n   AUTOSUBMIT_VERSION: '4.1.14'\n   TOTALJOBS: 1\n   MAXWAITINGJOBS: 1\nDEFAULT:\n   EXPID: 'a000'\n   HPCARCH: 'MARENOSTRUM5'\nPROJECT:\n   PROJECT_TYPE: None\n   PROJECT_DESTINATION: git_project\nGIT:\n   PROJECT_ORIGIN: ''\n   PROJECT_BRANCH: ''\n   PROJECT_COMMIT: ''\n   PROJECT_SUBMODULES: ''\n   FETCH_SINGLE_BRANCH: TRUE\n\nLOCAL:\n   PROJECT_PATH: ./\n\nPLATFORMS:\n   MARENOSTRUM5:\n     TYPE: slurm\n     HOST: gen1\n     PROJECT: /\n     # HPC_PROJECT_ROOT: /gpfs/projects\n     USER: root\n     QUEUE: normal\n     MAX_WALLCLOCK: 02:00\n     SCRATCH_DIR: /\n     PROCESSORS_PER_NODE: 1\n\nJOBS:\n   SIM:\n     SCRIPT: |\n       sleep 5\n     WALLCLOCK: "00:10"\n     RUNNING: chunk\n     CHECK: on_submission\n   POST:\n     SCRIPT: |\n         sleep 5\n     RUNNING: chunk\n     WALLCLOCK: "00:05"\n     CHECK: on_submission\n   TA:\n     SCRIPT: |\n         sleep 5\n     RUNNING: once\n     WALLCLOCK: "00:05"\n     CHECK: on_submission\n\nEXPERIMENT:\n   DATELIST: 19880101\n   MEMBERS: fc0\n   CHUNKSIZEUNIT: month\n   CHUNKSIZE: 1\n   NUMCHUNKS: 1\n   CALENDAR: standard\n   SPLITSIZEUNIT: day\n   SPLITSIZE: 1\n   SPLITPOLICY: flexible" >> /home/runner/autosubmit/a000/conf/minimal.yml'
          cat /home/runner/autosubmit/a000/conf/minimal.yml
          autosubmit create a000 -np
          autosubmit run a000


#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: ${{ matrix.python-version }}
#
#      - name: Install system dependencies
#        run: sudo apt-get install -y curl git graphviz rsync
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip packaging setuptools twine
#          pip install --upgrade -e .[all]
#
#      - name: Set up Git
#        run: |
#          # From: https://stackoverflow.com/questions/62960533/how-to-use-git-commands-during-a-github-action
#          # Set up dummy configuration for integration tests.
#          git --version
#          git config --global user.email "test@bsc.es"
#          git config --global user.name "GitHub Actions"

      # In GitHub Actions we run all the integration tests, including those that require
      # dependencies such as Docker (see `-m ''`, which means all markers). Read the
      # CONTRIBUTING.md file for details how to set up your environment to run these.
#      - name: Integration tests
#        run: |
#          pytest \
#            --cov=autosubmit --cov-config=.coveragerc \
#            --cov-report=xml:test/coverage.xml --cov-append \
#            test/integration \
#            -m ''
#
#      - name: Coverage report
#        run: |
#          coverage xml
#          coverage report
#
#      - name: Upload coverage artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: coverage_integration_py-${{ matrix.python-version }}
#          path: coverage.xml
#          retention-days: 7
