name: Correct creation of rocrate objects
run-name: ${{ github.actor }} is testing the rocrate🚀
on: [push]

jobs:
  setup-autosubmit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install system dependencies
        run: sudo apt-get install -y graphviz rsync curl

      - name: Install autosubmit
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          
      - name: Configure autosubmit
        run: |
          autosubmit configure
          autosubmit install

      - name: Create dummy experiment
        run: autosubmit expid -H "local" -d "GitHub Action validate RO-Crate"

      - name: Save rocrate.yml in experiment a000
        run: |
          mv .github/workflows/files/rocrate.yml /home/runner/autosubmit/a000/conf

      - name: Check that rocrate.yml is correctly created
        run: |
          ls /home/runner/autosubmit/a000/conf
          cat /home/runner/autosubmit/a000/conf/rocrate.yml

      - name: Update jobs_a000.yml
        run: |
          python -c "
          from pathlib import Path
          from ruamel.yaml import YAML
          
          yaml = YAML(typ='rt')

          yaml_file_path = Path('/home/runner/autosubmit/a000/conf/jobs_a000.yml')

          with open(yaml_file_path, 'r') as file:
              yaml_content = yaml.load(file)

          for job in yaml_content['JOBS']:
              yaml_content['JOBS'][job]['TASKS'] = 1
          with open(yaml_file_path, 'w') as file:
              yaml.dump(yaml_content, file)
          print(f\"Added 'TASKS: 1' to each job in {yaml_file_path}\")
          "

  run-experiment:
    runs-on: ubuntu-latest
    needs: setup-autosubmit
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install autosubmit
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Create and run autosubmit experiment
        run: |
          autosubmit create a000
          autosubmit run a000

  validate-rocrate:
    runs-on: ubuntu-latest
    needs: run-experiment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install roc-validator
        run: |
          python -m pip install --upgrade pip
          pip install roc-validator

      - name: Run roc-validator
        run: |
          rocrate-validator validate /home/runner/autosubmit/a000/tmp/ASLOGS/*.zip
